# after mapping an ontology to subclasses of gufo:Individual, look for subclasses in the ontology that are not mapped the same as the parent

prefix gist: <https://w3id.org/semanticarts/ns/ontology/gist/> 
prefix gistd: <https://w3id.org/semanticarts/ns/data/gist/> 
prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix skos: <http://www.w3.org/2004/02/skos/core#> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 

prefix gufo: <http://purl.org/nemo/gufo#> 
prefix ex: <https://example.org/>

select distinct ?message

where {  
  
  ?class rdfs:subClassOf ?gufoClass .         # all the gufo classes that ?class maps to
  filter(contains(str(?class),     "gist"))
  filter(contains(str(?gufoClass), "gufo"))
  
  
  filter not exists  { 
        ?class rdfs:subClassOf ?gufoClass2 .        # remove ones that are parents, leaving only the most granular mappings
        filter(contains(str(?class),      "gist"))
        filter(contains(str(?gufoClass2), "gufo"))
        ?gufoClass2 rdfs:subClassOf+ ?gufoClass .
        }
  
  # every subclass of ?class should also map to the same gufo Individual class as its parent
  
  ?subClass rdfs:subClassOf ?class .   # is within the mapped ontology
  
  filter not exists {?subClass rdfs:subClassOf ?gufoClass .}
  
  ?class     skos:prefLabel ?classLabel .
  ?subClass  skos:prefLabel ?subClassLabel .
  ?gufoClass rdfs:label     ?gufoClassLabel .
  
            
  
  bind(concat("gist ", ?classLabel, " is a subclass of gUFO ", ?gufoClassLabel, " so its subclass ", ?subClassLabel, " should also be a subclass, but it is not.") as ?message)
  
}
order by ?class

