# after mapping to subclasses of gufo:Type and inferring relationships, look for inconsistent mappings to Types
# run with reasoning turned on

prefix gist: <https://w3id.org/semanticarts/ns/ontology/gist/> 
prefix gistd: <https://w3id.org/semanticarts/ns/data/gist/> 
prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix skos: <http://www.w3.org/2004/02/skos/core#> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 

prefix gufo: <http://purl.org/nemo/gufo#> 
prefix ex: <https://example.org/>

select distinct ?message

where {
  
  values (?gufoClass          ?requiredSubClassType) {      # restriction on subclass of a class with type gufoClass     
          (gufo:AntiRigidType gufo:AntiRigidType)
          (gufo:Sortal        gufo:Sortal)    
          }
  
  ?class rdf:type ?gufoClass .
  filter(contains(str(?class),     "gist"))
  filter(contains(str(?gufoClass), "gufo"))
  
  ?subClass rdfs:subClassOf ?class .

  
  
  filter not exists {?subClass rdf:type ?requiredSubClassType .}
  
  ?class    skos:prefLabel ?classLabel .
  ?subClass skos:prefLabel ?subClassLabel .
  ?gufoType rdfs:label     ?gufoTypeLabel .
         
  
  bind(concat("gist ", ?classLabel, " is a gufo ", ?gufoTypeLabel, " but its subclass ", ?subClassLabel, " is not.") as ?message)
 
  }
order by ?class
