prefix gist: <https://w3id.org/semanticarts/ns/ontology/gist/>
prefix gistx: <https://w3id.org/semanticarts/ns/taxonomy/gist/>
prefix ontouml: <https://w3id.org/ontouml#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix xml: <http://www.w3.org/XML/1998/namespace>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix gufo: <http://purl.org/nemo/gufo#>

# Mixin With Same Rigidity 

# A class stereotyped as «Mixin» specialized only by other classes that have the same rigidity property, i.e., are all rigid or all anti-rigid.

# As all non-sortals, mixins aggregated individuals that follow different identity principles. Its distinguishing characteristic, though, is that is semi-rigid, i.e., it behaves as a rigid type for some individuals as an anti-rigid for others. This anti-pattern analyzes mixins that, despite their capabilities, only generalize types with the same rigidity.

SELECT DISTINCT ?invalid_class ?error_msg 
WHERE {

    ?invalid_class a gufo:Mixin .

    FILTER NOT EXISTS { ?invalid_class ^rdfs:subClassOf ?subclass1, ?subclass2 . ?subclass1 a gufo:AntiRigidType . ?subclass2 a gufo:RigidType }

    BIND("This class is an instance of the MixRig anti-pattern." AS ?error_msg)
    
}
