prefix gist: <https://w3id.org/semanticarts/ns/ontology/gist/>
prefix gistx: <https://w3id.org/semanticarts/ns/taxonomy/gist/>
prefix ontouml: <https://w3id.org/ontouml#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix xml: <http://www.w3.org/XML/1998/namespace>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix gufo: <http://purl.org/nemo/gufo#>

# Relator Mediating Rigid Types

# A «Relator» connected to one or more rigid types through mediations.
# When a type is connected to a mediation association, it means that it is externally dependent, i.e. for an individual to instantiate it, it must be related to another type. Usually, mediations define roles and roleMixins – anti-rigid types.

SELECT ?invalid ?error_msg
WHERE {

?invalid a gufo:Relator ;
    gufo:mediates ?rigid1 .
?rigid1 a gufo:RigidType .

BIND("This class is an instance of the RelRig anti-pattern, read more at https://ontouml.readthedocs.io/en/latest/anti-patterns/RelRig/index.html" AS ?error_msg)
}