# infer type relationships between a class and gufo classes

# ?class is any class that is mapped to a subclass of gufo Individual

prefix gist: <https://w3id.org/semanticarts/ns/ontology/gist/> 
prefix gistd: <https://w3id.org/semanticarts/ns/data/gist/> 
prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix skos: <http://www.w3.org/2004/02/skos/core#> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 

prefix gufo: <http://purl.org/nemo/gufo#> 
prefix ex: <https://example.org/>

# view the inferred relationships
# construct {?class rdf:type ?gufoSuperClass .}

# materialize the inferred relationships
 insert {graph ex:_NamedGraph_mapping {?class rdf:type ?gufoSuperClass .}}


where {
  
  ?class rdf:type ?gufoClass .
  
  filter(contains(str(?class),     "gist"))  # can be generalized to other ontologies mapped to gufo  
  filter(contains(str(?gufoClass), "gufo"))
  
  ?gufoClass rdfs:subClassOf+ ?gufoSuperClass .
  filter(!isBlank(?gufoSuperClass))
  filter not exists {?class rdf:type ?gufoSuperClass .}  # makes the query idempotent
  }

#order by ?class      # comment out to do insert
