# infer Type from subclass of Individual
# some gufo Individuals have a matching Type (e.g. Event and EventType)
# when a matching entry is missing, this script will find it and can insert it

prefix gist: <https://w3id.org/semanticarts/ns/ontology/gist/> 
prefix gistd: <https://w3id.org/semanticarts/ns/data/gist/> 
prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix skos: <http://www.w3.org/2004/02/skos/core#> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 

prefix gufo: <http://purl.org/nemo/gufo#> 

# view missing triples
#construct {?class rdf:type ?inferredType .}
#select ?class ?inferredType

# insert missing triples
 insert {graph ex:_NamedGraph_mapping {?class rdf:type ?inferredType .}}

where {

   values (?gufoIndividualClass    ?inferredType) {
           (gufo:AbstractIndividual gufo:AbstractIndividualType)
           (gufo:ConcreteIndividual gufo:ConcreteIndividualType)
           (gufo:Endurant           gufo:EndurantType          )
           (gufo:Event              gufo:EventType             )
           (gufo:Situation          gufo:SituationType         )
          }

   ?class rdfs:subClassOf ?gufoIndividualClass .
   filter not exists {?class rdf:type ?inferredType .}
   
}
#order by ?class
