prefix gist: <https://w3id.org/semanticarts/ns/ontology/gist/>
prefix gistx: <https://w3id.org/semanticarts/ns/taxonomy/gist/>
prefix ontouml: <https://w3id.org/ontouml#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix xml: <http://www.w3.org/XML/1998/namespace>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

# Kind Constraint 1
# A Kind cannot have an identity provider (Kind, Collective, Quality, Relator, Mode, or Quantity) as its direct or indirect super-type.

SELECT ?invalid ?error_msg
WHERE {

    ?invalid
        ontouml:stereotype ontouml:kind ;
        rdfs:subClassOf ?super_class_iri ;
        .

    ?super_class_iri
        ontouml:stereotype ?identity_provider_stereotype_iri ;
        .

    VALUES ?identity_provider_stereotype_iri {
        ontouml:kind
        ontouml:collective
        ontouml:quality
        ontouml:relator
        ontouml:mode
        ontouml:quantity
    }

    BIND("A Kind cannot have an identity prvider as its direct or indirect super-type" AS ?error_msg)
}
