prefix gist: <https://w3id.org/semanticarts/ns/ontology/gist/>
prefix gistx: <https://w3id.org/semanticarts/ns/taxonomy/gist/>
prefix ontouml: <https://w3id.org/ontouml#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix xml: <http://www.w3.org/XML/1998/namespace>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

# Anti-rigid classes may not be superclasses of Rigid or Semi-Rigid classes. 
# All results should be considered issues in the ontology. 

SELECT DISTINCT ?anti_rigid_class (GROUP_CONCAT(?non_anti_rigid_class; separator=', ') AS ?non_anti_rigid_subclasses) ?error_msg
WHERE {
?anti_rigid_class ontouml:stereotype gistx:_Rigidity_antirigid ;
    ^rdfs:subClassOf* ?non_anti_rigid_class .
FILTER NOT EXISTS {?non_anti_rigid_class ontouml:stereotype gistx:_Rigidity_antirigid}
BIND("Anti-Rigid classes may not be the superclass of any Semi-Rigid or Rigid classes." AS ?error_msg)
}
GROUP BY ?anti_rigid_class