prefix gist: <https://w3id.org/semanticarts/ns/ontology/gist/>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix gufo: <http://purl.org/nemo/gufo#>

# Category Constraint 2

# A «Category» is a rigid construct, therefore it cannot have as ancestor an anti-rigid type, as: «Role», «RoleMixin», «Phase».

SELECT ?invalid_class ?rigid_ancestor ?error_msg
WHERE{

    ?rigid_ancestor_type rdfs:subClassOf gufo:AntiRigidType .

    ?rigid_ancestor a ?rigid_ancestor_type .

    ?invalid_class a gufo:Category ;
        rdfs:subClassOf ?rigid_ancestor .
    
    BIND("A Category is a rigid construct, therefore it cannot have as ancestor an anti-rigid type." AS ?error_msg)
    
}
