prefix gist: <https://w3id.org/semanticarts/ns/ontology/gist/>
prefix gistx: <https://w3id.org/semanticarts/ns/taxonomy/gist/>
prefix ontouml: <https://w3id.org/ontouml#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix xml: <http://www.w3.org/XML/1998/namespace>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>


# from the nemo repository https://github.com/nemo-ufes/ufo-types/blob/master/models/sparql-queries.rq, reformatted for ours.
# Every specialization of endurant instantiates a single endurant type
# Example: Meeting spec Relator and Quality while iof Kind

select ?invalid ?error_msg
where {
    {
        select ?invalid (count(?invalid) as ?n)
        where {
            { ?invalid rdfs:subClassOf gufo:Object . }
            union { ?invalid rdfs:subClassOf gufo:Relator . }
            union { ?invalid rdfs:subClassOf gufo:Quality . }
            union { ?invalid rdfs:subClassOf gufo:ExtrinsicMode . }
            union { ?invalid rdfs:subClassOf gufo:IntrinsicMode . }
        }
        group by ?invalid
    }
    filter (?n > 1)
    BIND("This class is a subClass of multiple Endurant Classes, and its members will therefore instantiate multiple Endurant Types" AS ?error_msg)
}
