prefix gist: <https://w3id.org/semanticarts/ns/ontology/gist/>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix gufo: <http://purl.org/nemo/gufo#>

# from the nemo repository https://github.com/nemo-ufes/ufo-types/blob/master/models/sparql-queries.rq, reformatted.

# Every specialization of endurant instantiates a single endurant type.

select ?invalid ?error_msg
where {
    {
        select ?invalid (count(?invalid) as ?n)
        where {
                  { ?invalid rdf:type gufo:Category . }
            union { ?invalid rdf:type gufo:RoleMixin . }
            union { ?invalid rdf:type gufo:PhaseMixin . }
            union { ?invalid rdf:type gufo:Mixin . }
            union { ?invalid rdf:type gufo:Kind . }
            union { ?invalid rdf:type gufo:SubKind . }
            union { ?invalid rdf:type gufo:Role . }
            union { ?invalid rdf:type gufo:Phase . }
        }
        group by ?invalid
    }
    filter (?n > 1)
    BIND("This instance is of multiple Endurant Types." as ?error_msg)
    
}
