prefix gist: <https://w3id.org/semanticarts/ns/ontology/gist/>
prefix gistx: <https://w3id.org/semanticarts/ns/taxonomy/gist/>
prefix ontouml: <https://w3id.org/ontouml#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix xml: <http://www.w3.org/XML/1998/namespace>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix gufo: <http://purl.org/nemo/gufo#>

# Kind Constraint 1

# A Kind cannot have an identity provider as its direct or indirect super-type.

# This query only checks for gufo:Kind, as it is the only gUFO Type that provides identity. 

SELECT ?invalid_class ?superclass ?error_msg
WHERE {

    ?superclass a gufo:Kind .

    ?invalid_class a gufo:Kind ;
        rdfs:subClassOf+ ?superclass .

    BIND("A Kind cannot have an identity provider as its direct or indirect super-type" AS ?error_msg)
}
