prefix gist: <https://w3id.org/semanticarts/ns/ontology/gist/>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix gufo: <http://purl.org/nemo/gufo#>

# Kind Constraint 3

# A «Kind» cannot have types that aggregate individuals with different identity principles («Category», «RoleMixin» and «Mixin») as its direct or indirect subtypes.

SELECT ?invalid_class ?subclass ?error_msg
WHERE {

    VALUES ?diff_identity_aggregator {
        gufo:Category
        gufo:RoleMixin
        gufo:Mixin
    }

    ?invalid_class a gufo:Kind . 

    ?subclass a ?diff_identity_aggregator ;
        rdfs:subClassOf+ ?invalid_class .

    BIND("A Kind cannot have types that aggregate individuals with different identity principles (Category, RoleMixin, and Mixin) as its direct or indirect subtypes." AS ?error_msg)
}
