prefix gist: <https://w3id.org/semanticarts/ns/ontology/gist/>
prefix gistx: <https://w3id.org/semanticarts/ns/taxonomy/gist/>
prefix ontouml: <https://w3id.org/ontouml#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix xml: <http://www.w3.org/XML/1998/namespace>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix gufo: <http://purl.org/nemo/gufo#>

# Mixin Constraint 1

# A Mixin is a semi-rigid construct and therefore cannot have either a rigid (other than Category) or an anti-rigid type as an ancestor. 

SELECT ?invalid_class ?forbidden_ancestor ?error_msg
WHERE {

    VALUES ?forbidden_ancestor_type {
        gufo:Kind
        gufo:SubKind
        gufo:Phase
        gufo:PhaseMixin 
        gufo:Role 
        gufo:RoleMixin
    }

    ?forbidden_ancestor a ?forbidden_ancestor_type ;
        ^rdfs:subClassOf ?invalid_class .

    BIND("A Mixin is a semi-rigid construct and therefore cannot have either a rigid (other than Category) or an anti-rigid type as an ancestor." AS ?error_msg)
    
}
