prefix gist: <https://w3id.org/semanticarts/ns/ontology/gist/>
prefix gistx: <https://w3id.org/semanticarts/ns/taxonomy/gist/>
prefix ontouml: <https://w3id.org/ontouml#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix xml: <http://www.w3.org/XML/1998/namespace>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix gufo: <http://purl.org/nemo/gufo#>
 
# Phase Constraint 4

# A «Phase» cannot be a super-type of a rigid type.

SELECT ?invalid_class ?rigid_class ?error_msg
WHERE {

    ?rigid_type rdfs:subClassOf gufo:RigidType .

    ?rigid_class a ?rigid_type .

    ?invalid_class a gufo:Phase ;
        ^rdfs:subClassOf+ ?rigid_class .

    BIND("A Phase cannot be a superclass of a rigid class." AS ?error_msg)

}
