prefix gist: <https://w3id.org/semanticarts/ns/ontology/gist/>
prefix gistx: <https://w3id.org/semanticarts/ns/taxonomy/gist/>
prefix ontouml: <https://w3id.org/ontouml#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix xml: <http://www.w3.org/XML/1998/namespace>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix gufo: <http://purl.org/nemo/gufo#>

# from the nemo repository https://github.com/nemo-ufes/ufo-types/blob/master/models/sparql-queries.rq, reformatted for ours.

# Ultimate sortals cannot specialize other ultimate sortals

# Example Person spec Organization

SELECT DISTINCT ?invalid_class ?error_msg
WHERE {

    ?invalid_class rdf:type gufo:Kind .

    FILTER EXISTS { ?invalid_class rdfs:subClassOf+/rdf:type gufo:Kind . }

    BIND("This class is an ultimate sortal, but is the subclass of another ultimate sortal." AS ?error_msg)

}
