prefix gist: <https://w3id.org/semanticarts/ns/ontology/gist/>
prefix gistx: <https://w3id.org/semanticarts/ns/taxonomy/gist/>
prefix ontouml: <https://w3id.org/ontouml#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix xml: <http://www.w3.org/XML/1998/namespace>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix gufo: <http://purl.org/nemo/gufo#>

# Subkind Constraint 2

# Because it is a rigid type, a «Subkind» cannot have an anti-rigid type («Role», «Phase», «RoleMixin») as an ancestor.

SELECT ?invalid ?anti_rigid_superclass ?error_msg
WHERE {

    ?anti_rigid_type rdfs:subClassOf gufo:AntiRigidType .

    ?anti_rigid_superclass a ?anti_rigid_type .

    ?invalid a gufo:SubKind ;
        rdfs:subClassOf+ ?anti_rigid_superclass

    BIND ("A Subkind cannot have an anti-rigid type (Role, Phase, RoleMixin) as an ancestor." AS ?error_msg)
}