# finds subclasses of abstract types that are not abstract types
# (it seems like they should be)

prefix gist: <https://w3id.org/semanticarts/ns/ontology/gist/> 
prefix gistd: <https://w3id.org/semanticarts/ns/data/gist/> 
prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix skos: <http://www.w3.org/2004/02/skos/core#> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 

prefix gufo: <http://purl.org/nemo/gufo#> 

# view missing triples
select ?class ?subClass ?message

where {
  
    bind("class is Abstract but its subclass is not Abstract" as ?message)

   ?class rdf:type gufo:AbstractIndividualType .
  
   ?subClass rdfs:subClassOf* ?class .
  
   filter not exists {?subClass rdf:type gufo:AbstractIndividualType .}
  }
order by ?class ?subclass
