# check subclass consistency

prefix gist: <https://w3id.org/semanticarts/ns/ontology/gist/> 
prefix gistd: <https://w3id.org/semanticarts/ns/data/gist/> 
prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix skos: <http://www.w3.org/2004/02/skos/core#> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 

prefix gufo: <http://purl.org/nemo/gufo#> 
prefix ex: <https://example.org/>

select ?class ?gufoClass ?requiredSubClassType ?subClassInViolation

where {
  
  values (?gufoClass               ?requiredSubClassType) {
          (gufo:AbstractIndividual  gufo:AbstractIndividual)    
          (gufo:AntiRigidType       gufo:AntiRigidType)
          (gufo:Aspect              gufo:Aspect)
          (gufo:ConcreteIndividual  gufo:ConcreteIndividual)
          (gufo:Endurant            gufo:Endurant)
          (gufo:Event               gufo:Event)
          (gufo:Situation           gufo:Situation)
          (gufo:Sortal              gufo:Sortal)    
          }
  
  ?class rdf:type|rdfs:subClassOf ?gufoClass .
  filter(contains(str(?class), "gist"))
  
  ?subClassInViolation rdfs:subClassOf ?class .
  filter not exists {?subClassInViolation rdf:type|rdfs:subClassOf ?requiredSubClassType .}
  
  }
order by ?class
